apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
      - name: portfolio-service
        image: sidartasilva/portfolio-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5701
        - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: NodePort
  selector:
    app: portfolio-service
  ports:
  - name: hazelcast
    port: 5701
  - name: app
    port: 8085